#!/usr/bin/with-contenv bash
exec \
	s6-setuidgid container /usr/bin/Xtigervnc -desktop "${AppName}" -BlacklistThreshold 99999 -BlacklistTimeout 0 -localhost -rfbport 5900 -SecurityTypes None -AlwaysShared -AcceptKeyEvents -AcceptPointerEvents -AcceptSetDesktopSize -SendCutText -AcceptCutText :0
