#!/usr/bin/with-contenv bash
exec \
	s6-setuidgid container wait-for localhost:5900 -t 5 -- /usr/local/bin/easy-novnc --addr :8080 --host localhost --port 5900 --no-url-password --novnc-params "resize=remote"
